[package]
name = "ck3-index-jomini-oracle"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-or-later"
publish = false
default-run = "ck3-index-jomini-oracle"

[dependencies]
flate2 = { version = "=1.1.9", default-features = false, features = ["zlib-rs"] }
jomini = { version = "=0.35.0", default-features = false, features = ["envelope", "serde"] }
rawzip = "=0.5.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.114"
