// Code generated by tools/extract_on_actions.py; DO NOT EDIT.
// Source: ck3-tiger on_action.rs (CK3 1.15.0; 199 entries)
package indexer

const tigerOnActionTableVersion = "1.15.0"

var tigerOnActions = map[string]struct{}{
	"five_year_everyone_pulse": {},
	"five_year_playable_pulse": {},
	"five_year_struggle_playable_pulse": {},
	"on_absent_from_royal_court": {},
	"on_accolade_acclaimed_death": {},
	"on_accolade_acclaimed_removal": {},
	"on_accolade_create_squire": {},
	"on_accolade_created": {},
	"on_accolade_glory_change": {},
	"on_accolade_new_acclaimed_knight": {},
	"on_accolade_rank_change": {},
	"on_accolade_succession": {},
	"on_alliance_added": {},
	"on_alliance_broken": {},
	"on_alliance_removed": {},
	"on_apply_inherited_confederation": {},
	"on_army_combat_finished": {},
	"on_army_enter_province": {},
	"on_army_monthly": {},
	"on_artifact_broken_through_decay": {},
	"on_artifact_broken_through_effect": {},
	"on_artifact_changed_owner": {},
	"on_artifact_claim_gained": {},
	"on_artifact_claim_lost": {},
	"on_artifact_durability_low": {},
	"on_artifact_durability_very_low": {},
	"on_artifact_succession": {},
	"on_baron_found_or_created_for_title": {},
	"on_barter_action_completion": {},
	"on_barter_action_start": {},
	"on_barter_action_weekly": {},
	"on_barter_loot_delivered": {},
	"on_became_dynasty_head": {},
	"on_became_house_head": {},
	"on_become_independent_after_grant_title_at_vassal_limit": {},
	"on_betrothal_broken": {},
	"on_birth_child": {},
	"on_birth_father": {},
	"on_birth_mother": {},
	"on_birth_real_father": {},
	"on_birthday": {},
	"on_building_cancelled": {},
	"on_building_completed": {},
	"on_building_started": {},
	"on_character_culture_change": {},
	"on_character_faith_change": {},
	"on_combat_end_loser": {},
	"on_combat_end_winner": {},
	"on_combat_start": {},
	"on_combat_unit_join_side": {},
	"on_commander_combat_finished": {},
	"on_concubinage": {},
	"on_concubinage_end": {},
	"on_councillor_left": {},
	"on_councillors_swapped": {},
	"on_county_auto_granted_to_herder": {},
	"on_county_auto_granted_to_liege_culture": {},
	"on_county_auto_granted_to_local_culture": {},
	"on_county_culture_change": {},
	"on_county_faith_change": {},
	"on_county_occupied": {},
	"on_court_grandeur_level_changed": {},
	"on_court_language_changed": {},
	"on_court_type_changed": {},
	"on_courtier_decided_to_move_to_pool": {},
	"on_courtier_ready_to_move_to_pool": {},
	"on_culture_created": {},
	"on_culture_era_changed": {},
	"on_death": {},
	"on_defeat_barter_army": {},
	"on_defeat_raid_army": {},
	"on_diarch_change": {},
	"on_diarch_designation": {},
	"on_divorce": {},
	"on_domicile_building_cancelled": {},
	"on_domicile_building_completed": {},
	"on_domicile_building_started": {},
	"on_domicile_moved": {},
	"on_dynasty_created": {},
	"on_entered_diarchy": {},
	"on_explicit_claim_gain": {},
	"on_explicit_claim_lost": {},
	"on_faith_conversion": {},
	"on_faith_created": {},
	"on_faith_monthly": {},
	"on_game_start": {},
	"on_game_start_after_lobby": {},
	"on_game_start_with_tutorial": {},
	"on_government_change": {},
	"on_great_building_rebuilt": {},
	"on_great_holy_war_countdown_end": {},
	"on_great_holy_war_invalidation": {},
	"on_great_holy_war_participant_replaced": {},
	"on_guest_arrived_from_pool": {},
	"on_guest_ready_to_move_to_pool": {},
	"on_holding_razed": {},
	"on_holy_order_destroyed": {},
	"on_holy_order_hired": {},
	"on_holy_order_new_lease": {},
	"on_hook_used": {},
	"on_hostage_invalidated": {},
	"on_hostage_released": {},
	"on_hostage_taken": {},
	"on_house_aspiration_changed": {},
	"on_house_aspiration_upgraded": {},
	"on_house_in_admin_realm_became_dominant": {},
	"on_house_in_admin_realm_became_powerful": {},
	"on_house_relation_created": {},
	"on_house_relation_destroyed": {},
	"on_house_relation_level_changed": {},
	"on_imprison": {},
	"on_influence_level_gain": {},
	"on_influence_level_loss": {},
	"on_join_court": {},
	"on_join_war_as_secondary": {},
	"on_kurultai_succession_chaotic": {},
	"on_kurultai_succession_stable": {},
	"on_leave_court": {},
	"on_left_diarchy": {},
	"on_liege_government_change": {},
	"on_marriage": {},
	"on_mercenary_company_dismissed": {},
	"on_mercenary_company_hired": {},
	"on_merit_level_gain": {},
	"on_merit_level_loss": {},
	"on_migration_travel_end": {},
	"on_migration_war_end": {},
	"on_natural_death_second_chance": {},
	"on_noble_family_title_created": {},
	"on_perks_refunded": {},
	"on_piety_level_gain": {},
	"on_piety_level_loss": {},
	"on_player_royal_court_first_gained": {},
	"on_player_select_destiny_confirmed": {},
	"on_player_select_destiny_setup": {},
	"on_potential_great_holy_war_invalidation": {},
	"on_pregnancy_ended_mother": {},
	"on_pregnancy_father": {},
	"on_pregnancy_mother": {},
	"on_prestige_level_gain": {},
	"on_prestige_level_loss": {},
	"on_primary_title_change": {},
	"on_raid_action_completion": {},
	"on_raid_action_start": {},
	"on_raid_action_weekly": {},
	"on_raid_intent_invalidated": {},
	"on_raid_loot_delivered": {},
	"on_rank_down": {},
	"on_rank_up": {},
	"on_realm_capital_change": {},
	"on_release_from_prison": {},
	"on_ruler_designer_finished": {},
	"on_scheme_agent_discovered": {},
	"on_scheme_discovered": {},
	"on_scheme_opportunity_changed": {},
	"on_siege_completion": {},
	"on_siege_looting": {},
	"on_stress_level_1": {},
	"on_stress_level_2": {},
	"on_stress_level_3": {},
	"on_stress_level_4": {},
	"on_stress_level_reduced": {},
	"on_title_destroyed": {},
	"on_title_gain": {},
	"on_title_gain_inheritance": {},
	"on_title_gain_usurpation": {},
	"on_title_lost": {},
	"on_tradition_added": {},
	"on_tradition_removed": {},
	"on_travel_activity_arrival_too_late": {},
	"on_travel_activity_complete": {},
	"on_travel_activity_estimated_arrival_too_late": {},
	"on_travel_activity_invalidated": {},
	"on_travel_leader_removed": {},
	"on_travel_plan_abort": {},
	"on_travel_plan_arrival": {},
	"on_travel_plan_cancel": {},
	"on_travel_plan_complete": {},
	"on_travel_plan_movement": {},
	"on_travel_plan_start": {},
	"on_trigger_court_events": {},
	"on_vassal_change": {},
	"on_vassal_gained": {},
	"on_war_invalidated": {},
	"on_war_started": {},
	"on_war_transferred": {},
	"on_war_white_peace": {},
	"on_war_won_attacker": {},
	"on_war_won_defender": {},
	"quarterly_playable_pulse": {},
	"random_yearly_everyone_pulse": {},
	"random_yearly_playable_pulse": {},
	"three_year_playable_pulse": {},
	"three_year_pool_pulse": {},
	"three_yearly_culture_pulse": {},
	"yearly_culture_pulse": {},
	"yearly_global_pulse": {},
	"yearly_playable_pulse": {},
	"yearly_struggle_playable_pulse": {},
}

var tigerOnActionDirect = map[string]tigerOnActionDirectSeed{
	"on_absent_from_royal_court": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "value", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"on_accolade_acclaimed_death": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "accolade", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_acclaimed_knight", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "new_accolade_type", StaticType: "bool", Kind: TigerOnActionValueKindBool},
		},
	},
	"on_accolade_create_squire": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "accolade", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_acclaimed_knight", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "new_accolade_type", StaticType: "bool", Kind: TigerOnActionValueKindBool},
			tigerOnActionBindingSeed{Name: "new_owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_accolade_created": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "accolade", Kind: TigerOnActionValueKindScope},
	},
	"on_accolade_glory_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "accolade", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "glory", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"on_accolade_new_acclaimed_knight": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "accolade", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "glory", StaticType: "value", Kind: TigerOnActionValueKindValue},
			tigerOnActionBindingSeed{Name: "new_accolade_type", StaticType: "bool", Kind: TigerOnActionValueKindBool},
			tigerOnActionBindingSeed{Name: "new_acclaimed_knight", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_accolade_rank_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "accolade", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "positive", StaticType: "bool", Kind: TigerOnActionValueKindBool},
		},
	},
	"on_accolade_succession": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "accolade", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "new_owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_alliance_added": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "none", Kind: TigerOnActionValueKindNone},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "first", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "second", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_alliance_broken": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "none", Kind: TigerOnActionValueKindNone},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "first", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "second", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
		Lists: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "first", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "second", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_apply_inherited_confederation": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_army_combat_finished": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "combat_side", StaticType: "combat_side", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "victory", StaticType: "bool", Kind: TigerOnActionValueKindBool},
		},
		Lists: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "commanders", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "knights", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_army_monthly": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "army", StaticType: "army", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_artifact_broken_through_decay": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "artifact", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_artifact_changed_owner": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "artifact", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "old_owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_artifact_claim_gained": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "artifact", StaticType: "artifact", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_artifact_durability_low": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope, Review: true},
	},
	"on_artifact_succession": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "artifact", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "old_owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "old_primary", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_baron_found_or_created_for_title": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "liege", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_barter_action_completion": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "barterer", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barony", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "county", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "value", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"on_barter_action_start": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "barterer", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barony", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "county", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_barter_loot_delivered": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "barterer", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barter_loot", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"on_became_dynasty_head": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "dynasty", StaticType: "dynasty", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_became_house_head": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "house", StaticType: "dynasty_house", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_become_independent_after_grant_title_at_vassal_limit": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "actor", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "recipient", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_betrothal_broken": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "second", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "reason", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_birth_child": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "child", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "mother", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "real_father", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "father", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "is_bastard", StaticType: "bool", Kind: TigerOnActionValueKindBool},
		},
	},
	"on_birth_mother": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "child", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "mother", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "real_father", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "father", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_birthday": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_building_cancelled": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "province", Kind: TigerOnActionValueKindScope},
	},
	"on_building_completed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "province", Kind: TigerOnActionValueKindScope},
	},
	"on_building_started": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "province", Kind: TigerOnActionValueKindScope},
	},
	"on_character_culture_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_combat_end_winner": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "combat_side", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "wipe", StaticType: "bool", Kind: TigerOnActionValueKindBool},
		},
	},
	"on_combat_start": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "combat", Kind: TigerOnActionValueKindScope},
	},
	"on_combat_unit_join_side": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "combat_side", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "army", StaticType: "army", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_commander_combat_finished": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "combat_side", StaticType: "combat_side", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "victory", StaticType: "bool", Kind: TigerOnActionValueKindBool},
		},
	},
	"on_concubinage": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "concubine", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_concubinage_end": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "concubine", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "reason", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_councillor_left": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_employer", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "council_task", StaticType: "council_task", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "councillor", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_councillors_swapped": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "councillor", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "councillor_liege", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_county_auto_granted_to_herder": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "actor", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "recipient", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_county_auto_granted_to_liege_culture": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "culture", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "actor", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "landed_title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_county_culture_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_culture", StaticType: "culture", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_county_faith_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_faith", StaticType: "faith", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_county_occupied": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "county", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barony", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "previous_controller", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "war", StaticType: "war", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_court_grandeur_level_changed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_value", StaticType: "value", Kind: TigerOnActionValueKindValue},
			tigerOnActionBindingSeed{Name: "new_value", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"on_court_language_changed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_courtier_decided_to_move_to_pool": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "courtier", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "liege", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
		Lists: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "characters", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_culture_created": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "culture", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "founder", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_culture_era_changed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "culture", Kind: TigerOnActionValueKindScope},
	},
	"on_death": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "killer", StaticType: "character", Kind: TigerOnActionValueKindScope, Review: true},
		},
	},
	"on_defeat_barter_army": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "barterer", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "receiver", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barter_loot", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"on_defeat_raid_army": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "raider", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "receiver", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_diarch_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "reason", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
			tigerOnActionBindingSeed{Name: "old_diarch", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_diarch_designation": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "former_designated_diarch", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_divorce": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "spouse", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "reason", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_domicile_building_started": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "domicile", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_domicile_moved": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "domicile", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "owner", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_dynasty_created": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "dynasty", Kind: TigerOnActionValueKindScope},
		Review: true,
	},
	"on_entered_diarchy": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "reason", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_explicit_claim_gain": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "transfer_type", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_explicit_claim_lost": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_faith_created": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_faith", StaticType: "faith", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_faith_monthly": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "faith", Kind: TigerOnActionValueKindScope},
	},
	"on_game_start": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "none", Kind: TigerOnActionValueKindNone},
	},
	"on_government_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_government", StaticType: "government_type", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_great_building_rebuilt": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "province", StaticType: "province", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_great_holy_war_participant_replaced": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "great_holy_war", StaticType: "ghw", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "replacement", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_guest_arrived_from_pool": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "guest", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "host", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
		Lists: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "characters", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_guest_ready_to_move_to_pool": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "guest", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "host", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "destination", StaticType: "province", Kind: TigerOnActionValueKindScope, Review: true},
		},
		Lists: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "characters", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_holding_razed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "province", StaticType: "province", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_holy_order_destroyed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "faith", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "leader", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_holy_order_hired": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "holy_order", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "patron", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "actor", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_holy_order_new_lease": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "holy_order", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "patron", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barony", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_hook_used": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "target", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_hostage_invalidated": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "warden", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "home_court", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "imprisoner", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "reason", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_hostage_taken": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "hostage", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "warden", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "home_court", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_house_aspiration_upgraded": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "house", StaticType: "dynasty_house", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_house_in_admin_realm_became_powerful": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "dynasty_house", Kind: TigerOnActionValueKindScope},
	},
	"on_house_relation_created": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "house_relation", Kind: TigerOnActionValueKindScope},
	},
	"on_imprison": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "imprisoner", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_influence_level_gain": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_join_court": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "new_employer", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "old_employer", StaticType: "character", Kind: TigerOnActionValueKindScope, Review: true},
		},
	},
	"on_join_war_as_secondary": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "war", StaticType: "war", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_kurultai_succession_stable": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "was_kurultai", StaticType: "bool", Kind: TigerOnActionValueKindBool},
		},
		Lists: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "kurultai_members", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "obedient_kurultai", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "disobedient_kurultai", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_leave_court": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_employer", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_left_diarchy": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_diarch", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_liege_government_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_marriage": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "spouse", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_mercenary_company_dismissed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "mercenary_company", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_employer", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_mercenary_company_hired": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "mercenary_company", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "employer", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_merit_level_gain": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_migration_travel_end": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "actor", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "recipient", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "target_title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "domain", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_migration_war_end": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "actor", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "recipient", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "target_title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "domain", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "war", StaticType: "war", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_natural_death_second_chance": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_noble_family_title_created": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_perks_refunded": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_player_royal_court_first_gained": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_player_select_destiny_confirmed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "destiny_type_flag", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
			tigerOnActionBindingSeed{Name: "previous_player_character", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "previous_player_heir", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_player_select_destiny_setup": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "predecessor", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "heir", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_potential_great_holy_war_invalidation": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "ghw", Kind: TigerOnActionValueKindScope},
	},
	"on_pregnancy_mother": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "mother", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "real_father", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "father", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_primary_title_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "previous_title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_raid_action_start": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "raider", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barony", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "county", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_raid_intent_invalidated": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "raider", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_raid_loot_delivered": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "army", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "raider", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_realm_capital_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_capital", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_ruler_designer_finished": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_scheme_agent_discovered": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "scheme", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "agent", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_scheme_discovered": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "scheme", Kind: TigerOnActionValueKindScope},
	},
	"on_scheme_opportunity_changed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "scheme", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_value", StaticType: "value", Kind: TigerOnActionValueKindValue},
			tigerOnActionBindingSeed{Name: "new_value", StaticType: "value", Kind: TigerOnActionValueKindValue},
			tigerOnActionBindingSeed{Name: "scheme", StaticType: "scheme", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_siege_completion": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "county", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barony", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "previous_controller", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "war", StaticType: "war", Kind: TigerOnActionValueKindScope},
		},
		Lists: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "occupied_baronies", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_siege_looting": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "county", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "barony", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "previous_controller", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_stress_level_reduced": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_title_destroyed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "landed_title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_title_gain": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "previous_holder", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "transfer_type", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_title_lost": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "title", StaticType: "landed_title", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "new_holder", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "transfer_type", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_tradition_removed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "culture", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "tradition", StaticType: "flag", Kind: TigerOnActionValueKindFlag, Review: true},
		},
	},
	"on_travel_activity_arrival_too_late": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "travel_plan", StaticType: "travel_plan", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_travel_activity_complete": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope, Review: true},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "travel_plan", StaticType: "travel_plan", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_travel_activity_estimated_arrival_too_late": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "travel_plan", StaticType: "travel_plan", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "estimated_arrival_diff_days", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"on_travel_activity_invalidated": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope, Review: true},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "travel_plan", StaticType: "travel_plan", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_travel_leader_removed": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "travel_plan", StaticType: "travel_plan", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "old_travel_leader", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_travel_plan_movement": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_trigger_court_events": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"on_vassal_change": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "old_liege", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"on_vassal_gained": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "vassal", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "old_liege", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "transfer_type", StaticType: "flag", Kind: TigerOnActionValueKindFlag},
		},
	},
	"on_war_started": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "casus_belli", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "attacker", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "defender", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "claimant", StaticType: "character", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "war", StaticType: "war", Kind: TigerOnActionValueKindScope, Review: true},
		},
	},
	"on_war_transferred": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "war", StaticType: "war", Kind: TigerOnActionValueKindScope},
			tigerOnActionBindingSeed{Name: "defender", StaticType: "character", Kind: TigerOnActionValueKindScope},
		},
	},
	"quarterly_playable_pulse": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "quarter", StaticType: "value", Kind: TigerOnActionValueKindValue},
		},
	},
	"yearly_culture_pulse": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "culture", Kind: TigerOnActionValueKindScope},
	},
	"yearly_global_pulse": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "none", Kind: TigerOnActionValueKindNone},
	},
	"yearly_playable_pulse": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
	},
	"yearly_struggle_playable_pulse": {
		Root: tigerOnActionBindingSeed{Name: "root", StaticType: "character", Kind: TigerOnActionValueKindScope},
		Named: []tigerOnActionBindingSeed{
			tigerOnActionBindingSeed{Name: "struggle", StaticType: "struggle", Kind: TigerOnActionValueKindScope},
		},
	},
}

var tigerOnActionAliases = map[string]tigerOnActionAliasSeed{
	"five_year_everyone_pulse": {Target: "yearly_playable_pulse"},
	"five_year_playable_pulse": {Target: "yearly_playable_pulse"},
	"five_year_struggle_playable_pulse": {Target: "yearly_struggle_playable_pulse"},
	"on_accolade_acclaimed_removal": {Target: "on_accolade_acclaimed_death"},
	"on_alliance_removed": {Target: "on_alliance_added"},
	"on_army_enter_province": {Target: "on_army_monthly"},
	"on_artifact_broken_through_effect": {Target: "on_artifact_broken_through_decay"},
	"on_artifact_claim_lost": {Target: "on_artifact_claim_gained"},
	"on_artifact_durability_very_low": {Target: "on_artifact_broken_through_decay"},
	"on_barter_action_weekly": {Target: "on_barter_action_start"},
	"on_birth_father": {Target: "on_birth_mother"},
	"on_birth_real_father": {Target: "on_birth_mother"},
	"on_character_faith_change": {Target: "on_faith_created"},
	"on_combat_end_loser": {Target: "on_combat_end_winner"},
	"on_county_auto_granted_to_local_culture": {Target: "on_county_auto_granted_to_liege_culture"},
	"on_court_type_changed": {Target: "on_court_language_changed"},
	"on_courtier_ready_to_move_to_pool": {Target: "on_courtier_decided_to_move_to_pool"},
	"on_domicile_building_cancelled": {Target: "on_domicile_building_started"},
	"on_domicile_building_completed": {Target: "on_domicile_building_started"},
	"on_faith_conversion": {Target: "on_faith_created"},
	"on_game_start_after_lobby": {Target: "on_game_start"},
	"on_game_start_with_tutorial": {Target: "on_game_start"},
	"on_great_holy_war_countdown_end": {Target: "on_potential_great_holy_war_invalidation"},
	"on_great_holy_war_invalidation": {Target: "on_potential_great_holy_war_invalidation"},
	"on_hostage_released": {Target: "on_hostage_taken"},
	"on_house_aspiration_changed": {Target: "on_house_aspiration_upgraded"},
	"on_house_in_admin_realm_became_dominant": {Target: "on_house_in_admin_realm_became_powerful"},
	"on_house_relation_destroyed": {Target: "on_house_relation_created"},
	"on_house_relation_level_changed": {Target: "on_house_relation_created"},
	"on_influence_level_loss": {Target: "on_influence_level_gain"},
	"on_kurultai_succession_chaotic": {Target: "on_kurultai_succession_stable"},
	"on_merit_level_loss": {Target: "on_merit_level_gain"},
	"on_piety_level_gain": {Target: "on_influence_level_gain"},
	"on_piety_level_loss": {Target: "on_influence_level_gain"},
	"on_pregnancy_ended_mother": {Target: "on_pregnancy_mother"},
	"on_pregnancy_father": {Target: "on_pregnancy_mother"},
	"on_prestige_level_gain": {Target: "on_influence_level_gain"},
	"on_prestige_level_loss": {Target: "on_influence_level_gain"},
	"on_raid_action_completion": {Target: "on_raid_action_start"},
	"on_raid_action_weekly": {Target: "on_raid_action_start"},
	"on_rank_down": {Target: "on_explicit_claim_lost"},
	"on_rank_up": {Target: "on_explicit_claim_lost"},
	"on_release_from_prison": {Target: "on_imprison"},
	"on_stress_level_1": {Target: "on_stress_level_reduced"},
	"on_stress_level_2": {Target: "on_stress_level_reduced"},
	"on_stress_level_3": {Target: "on_stress_level_reduced"},
	"on_stress_level_4": {Target: "on_stress_level_reduced"},
	"on_title_gain_inheritance": {Target: "on_title_gain"},
	"on_title_gain_usurpation": {Target: "on_title_gain"},
	"on_tradition_added": {Target: "on_tradition_removed"},
	"on_travel_plan_abort": {Target: "on_travel_plan_movement"},
	"on_travel_plan_arrival": {Target: "on_travel_plan_movement"},
	"on_travel_plan_cancel": {Target: "on_travel_plan_movement"},
	"on_travel_plan_complete": {Target: "on_travel_plan_movement"},
	"on_travel_plan_start": {Target: "on_travel_plan_movement"},
	"on_war_invalidated": {Target: "on_war_started"},
	"on_war_white_peace": {Target: "on_war_started"},
	"on_war_won_attacker": {Target: "on_war_started"},
	"on_war_won_defender": {Target: "on_war_started"},
	"random_yearly_everyone_pulse": {Target: "yearly_playable_pulse"},
	"random_yearly_playable_pulse": {Target: "yearly_playable_pulse"},
	"three_year_playable_pulse": {Target: "yearly_playable_pulse"},
	"three_year_pool_pulse": {Target: "yearly_playable_pulse"},
	"three_yearly_culture_pulse": {Target: "yearly_culture_pulse"},
}
// 199 on_action entries (135 direct, 64 aliases; 11 list bindings)
