"""Generate CK3 define names from the current vanilla define source files.

CK3 defines are direct fields inside top-level N* namespaces.  The source
files are authoritative for existence.
"""

import argparse
import json
import pathlib
import re


NAMESPACE = re.compile(r"^\s*(N[A-Za-z0-9_]+)\s*=\s*\{")
PENDING_NAMESPACE = re.compile(r"^\s*(N[A-Za-z0-9_]+)\s*=\s*$")
# A small set of Jomini graphics defines use digit-prefixed field names, so
# accept every non-whitespace key token at namespace depth one.
KEY = re.compile(r"^\s*([^\s=]+)\s*=")


def code_portion(line: str) -> str:
    """Drop line comments; defines do not use multiline string literals."""
    return line.split("#", 1)[0]


def extract_file(path: pathlib.Path) -> set[str]:
    names: set[str] = set()
    depth = 0
    namespace = ""
    namespace_depth = -1
    pending_namespace = ""
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        # Paradox define files may start with a UTF-8 BOM; it is not part of
        # the namespace identifier.
        line = code_portion(raw.lstrip("\ufeff"))
        if not namespace:
            if pending_namespace:
                if line.lstrip().startswith("{"):
                    namespace = pending_namespace
                    pending_namespace = ""
                    depth += line.count("{") - line.count("}")
                    namespace_depth = depth
                continue
            match = NAMESPACE.match(line)
            if match:
                namespace = match.group(1)
                depth += line.count("{") - line.count("}")
                namespace_depth = depth
                continue
            match = PENDING_NAMESPACE.match(line)
            if match:
                pending_namespace = match.group(1)
            continue

        if depth == namespace_depth:
            match = KEY.match(line)
            if match:
                names.add(f"@{namespace}|{match.group(1)}")

        depth += line.count("{") - line.count("}")
        if depth < namespace_depth:
            namespace = ""
            namespace_depth = -1
    return names


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    defines_dir = args.game / "common" / "defines"
    files = sorted(defines_dir.rglob("*.txt"))
    if not files:
        raise SystemExit(f"missing current CK3 define sources: {defines_dir}")
    names = set().union(*(extract_file(path) for path in files))

    lines = [
        "// Code generated by tools/extract_engine_defines.py; DO NOT EDIT.",
        f"// Source: CK3 1.19 common/defines ({len(files)} current vanilla files, {len(names)} entries).",
        "",
        "package indexer",
        "",
        "// engineDefines contains CK3 1.19 @Namespace|KEY define names.",
        "var engineDefines = map[string]struct{}{",
    ]
    for name in sorted(names):
        lines.append(f"\t{json.dumps(name)}: {{}},")
    lines += ["}", "", f"// {len(names)} define entries"]
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
