"""Extract trigger usage examples from CK3's triggers.log dump."""

import re, os, sys

def main():
    base = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(base, "..", "..", "..", "logs", "triggers.log"),
        os.path.join(base, "..", "..", "logs", "triggers.log"),
    ]
    logpath = None
    for c in candidates:
        if os.path.exists(c):
            logpath = c
            break
    if not logpath:
        print("// ERROR: triggers.log not found", file=sys.stderr)
        return

    with open(logpath, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    sections = content.split("--------------------")
    entries = []
    seen = set()

    for section in sections:
        lines = [l.strip() for l in section.strip().split('\n') if l.strip()]
        if not lines:
            continue
        first = lines[0]
        m = re.match(r'(\w+)\s*-\s*(.*)', first)
        if not m:
            continue
        name = m.group(1).strip()
        desc = m.group(2).strip()
        if name in seen:
            continue
        seen.add(name)

        example = ""
        for line in lines[1:]:
            if '=' in line and not line.startswith("Supported Scopes"):
                ex = line.strip()
                if ex.startswith(name):
                    example = ex
                    break
        entries.append((name, desc, example))

    lines = []
    lines.append("// Code generated by tools/extract_trigger_examples.py; DO NOT EDIT.")
    lines.append(f"// Source: CK3 triggers.log ({len(entries)} triggers)")
    lines.append("")
    lines.append("package indexer")
    lines.append("")
    lines.append("var triggerExamples = map[string]struct{Desc,Example string}{")
    for name, desc, example in sorted(entries):
        d = desc.replace("`", "'").replace("\n", " ").replace("\r", "").replace("\ufffd", "?")
        if example:
            ex = example.replace("`", "'").replace("\n", " ").replace("\r", "").replace("\ufffd", "?")
            lines.append(f'\t"{name}": {{Desc: `{d}`, Example: `{ex}`}},')
        else:
            lines.append(f'\t"{name}": {{Desc: `{d}`}},')

    lines.append("}")
    lines.append(f"// {len(entries)} trigger entries")

    for line in lines:
        print(line)

if __name__ == "__main__":
    main()
