"""Generate conservative trigger/effect usage documentation from CK3 logs.

The game documentation logs publish examples and prose, but do not publish a
complete machine-readable value grammar. This generator therefore records only
those documented facts; it never assigns a guessed boolean/block/vbv/etc.
shape category.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
from collections import defaultdict


ENTRY = re.compile(r"^([a-z0-9_]+)\s*-\s*(.*)$", re.IGNORECASE)
DIVIDER = "--------------------"


def documentation_entries(path: pathlib.Path, kind: str) -> list[dict[str, object]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    out: list[dict[str, object]] = []
    for section in text.split(DIVIDER):
        lines = [line.strip() for line in section.splitlines() if line.strip()]
        if not lines:
            continue
        match = ENTRY.match(lines[0])
        if not match:
            continue
        name, description = match.groups()
        name = name.lower()
        examples: list[str] = []
        for line in lines[1:]:
            # Keep only direct, current documentation examples for this key.
            # Other prose can describe related keys or a surrounding context.
            if line.startswith(name) and "=" in line and line not in examples:
                examples.append(line)
        out.append(
            {
                "name": name,
                "kind": kind,
                "description": description.strip(),
                "examples": examples,
                "source": f"engine_logs/{path.name}",
            }
        )
    return out


def go(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--logs", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for filename, kind in (("triggers.log", "trigger"), ("effects.log", "effect")):
        path = args.logs / filename
        if not path.is_file():
            raise SystemExit(f"missing CK3 engine documentation: {path}")
        for entry in documentation_entries(path, kind):
            grouped[str(entry["name"])].append(entry)

    lines = [
        "// Code generated by tools/extract_engine_shapes.py; DO NOT EDIT.",
        "// Source: CK3 1.19 triggers.log and effects.log.",
        "",
        "package indexer",
        "",
        "// ShapeDocumentation is a direct current-engine documentation entry.",
        "// It intentionally records no inferred exhaustive value grammar.",
        "type ShapeDocumentation struct {",
        "\tRuleKind    string   `json:\"rule_kind\"`",
        "\tDescription string   `json:\"description,omitempty\"`",
        "\tExamples    []string `json:\"examples,omitempty\"`",
        "\tSource      string   `json:\"source\"`",
        "}",
        "",
        "// ShapeLookup contains only CK3 1.19 documented usage facts for a key.",
        "type ShapeLookup struct {",
        "\tKey           string               `json:\"key\"`",
        "\tEvidenceKind  string               `json:\"evidence_kind\"`",
        "\tDocumentation []ShapeDocumentation `json:\"documentation\"`",
        "}",
        "",
        "const engineShapeTableVersion = \"1.19.0-engine-log\"",
        "",
        "var engineShapeData = map[string]ShapeLookup{",
    ]
    for name in sorted(grouped):
        entries = sorted(grouped[name], key=lambda entry: str(entry["kind"]))
        lines.append(f"\t{go(name)}: {{")
        lines.append(f"\t\tKey: {go(name)},")
        lines.append('\t\tEvidenceKind: "documented_usage",')
        lines.append("\t\tDocumentation: []ShapeDocumentation{")
        for entry in entries:
            lines.append("\t\t\t{")
            lines.append(f"\t\t\t\tRuleKind: {go(entry['kind'])},")
            lines.append(f"\t\t\t\tDescription: {go(entry['description'])},")
            examples = entry["examples"]
            if examples:
                lines.append("\t\t\t\tExamples: []string{")
                for example in examples:
                    lines.append(f"\t\t\t\t\t{go(example)},")
                lines.append("\t\t\t\t},")
            lines.append(f"\t\t\t\tSource: {go(entry['source'])},")
            lines.append("\t\t\t},")
        lines.append("\t\t},")
        lines.append("\t},")
    lines.extend(["}", "", f"// {len(grouped)} documented CK3 1.19 trigger/effect keys"])
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
