"""Extract effect usage examples from CK3's effects.log dump.

The generated data supplements tigerShapeData with actual script examples showing
the block parameter format.

Usage: python extract_effect_examples.py > ../internal/indexer/effect_examples.gen.go
"""

import re, os, sys

def main():
    # Find the log file
    base = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(base, "..", "..", "..", "logs", "effects.log"),
        os.path.join(base, "..", "..", "logs", "effects.log"),
    ]
    logpath = None
    for c in candidates:
        if os.path.exists(c):
            logpath = c
            break
    if not logpath:
        print("// ERROR: effects.log not found", file=sys.stderr)
        return

    with open(logpath, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    # Split by section markers
    sections = content.split("--------------------")
    entries = []
    seen = set()

    for section in sections:
        lines = [l.strip() for l in section.strip().split('\n') if l.strip()]
        if not lines:
            continue

        # First line is: "effect_name - Description"
        first = lines[0]
        m = re.match(r'(\w+)\s*-\s*(.*)', first)
        if not m:
            continue

        name = m.group(1).strip()
        desc = m.group(2).strip()
        if name in seen:
            continue
        seen.add(name)

        # Find usage example: lines containing '='
        example = ""
        for line in lines[1:]:
            if '=' in line and not line.startswith("Supported Scopes"):
                # Clean up the example
                ex = line.strip()
                if ex.startswith(name):
                    example = ex
                    break

        entries.append((name, desc, example))

    lines = []
    lines.append("// Code generated by tools/extract_effect_examples.py; DO NOT EDIT.")
    lines.append(f"// Source: CK3 effects.log ({len(entries)} effects)")
    lines.append("")
    lines.append("package indexer")
    lines.append("")
    lines.append("// effectExamples maps effect names to usage examples from the game dump.")
    lines.append("var effectExamples = map[string]struct{Desc,Example string}{")
    for name, desc, example in sorted(entries):
        d = desc.replace("`", "'").replace("\n", " ").replace("\r", "").replace("\ufffd", "?")
        if example:
            ex = example.replace("`", "'").replace("\n", " ").replace("\r", "").replace("\ufffd", "?")
            lines.append(f'\t"{name}": {{Desc: `{d}`, Example: `{ex}`}},')
        else:
            lines.append(f'\t"{name}": {{Desc: `{d}`}},')

    lines.append("}")
    lines.append(f"// {len(entries)} effect entries")

    for line in lines:
        print(line)

if __name__ == "__main__":
    main()
