"""Extract scope-to-scope transitions from ck3-tiger targets.rs."""

import re, os

BASE = os.path.dirname(os.path.abspath(__file__))
TIER = os.path.join(BASE, "..", "external", "ck3-tiger", "src", "ck3", "tables")

# The scope constants from scope_data.gen.go
SCOPE_TO_GO = {
    "Accolade": "ScopeAccolade", "AccoladeType": "ScopeAccoladeType",
    "Activity": "ScopeActivity", "ActivityType": "ScopeActivityType",
    "AgentSlot": "ScopeAgentSlot", "Army": "ScopeArmy",
    "Artifact": "ScopeArtifact", "CasusBelli": "ScopeCasusBelli",
    "CasusBelliType": "ScopeCasusBelliType", "Character": "ScopeCharacter",
    "Combat": "ScopeCombat", "CombatSide": "ScopeCombatSide",
    "Confederation": "ScopeConfederation", "ConfederationType": "ScopeConfederationType",
    "CouncilTask": "ScopeCouncilTask", "CourtPosition": "ScopeCourtPosition",
    "CourtPositionType": "ScopeCourtPositionType", "Culture": "ScopeCulture",
    "CultureInnovation": "ScopeCultureInnovation",
    "CulturePillar": "ScopeCulturePillar",
    "CultureTradition": "ScopeCultureTradition", "Decision": "ScopeDecision",
    "Doctrine": "ScopeDoctrine", "Domicile": "ScopeDomicile",
    "Dynasty": "ScopeDynasty", "DynastyHouse": "ScopeDynastyHouse",
    "Epidemic": "ScopeEpidemic", "EpidemicType": "ScopeEpidemicType",
    "Faction": "ScopeFaction", "Faith": "ScopeFaith",
    "GeographicalRegion": "ScopeGeographicalRegion",
    "GovernmentType": "ScopeGovernmentType",
    "GreatHolyWar": "ScopeGreatHolyWar", "GreatProject": "ScopeGreatProject",
    "GreatProjectType": "ScopeGreatProjectType",
    "HoldingType": "ScopeHoldingType", "HolyOrder": "ScopeHolyOrder",
    "HouseAspiration": "ScopeHouseAspiration",
    "HouseRelation": "ScopeHouseRelation",
    "HouseRelationLevel": "ScopeHouseRelationLevel",
    "HouseRelationType": "ScopeHouseRelationType",
    "Inspiration": "ScopeInspiration", "LandedTitle": "ScopeTitle",
    "Legend": "ScopeLegend", "LegendType": "ScopeLegendType",
    "MercenaryCompany": "ScopeMercenaryCompany",
    "ProjectContribution": "ScopeProjectContribution",
    "Province": "ScopeProvince", "Regiment": "ScopeRegiment",
    "Religion": "ScopeReligion", "Scheme": "ScopeScheme",
    "Secret": "ScopeSecret", "Situation": "ScopeSituation",
    "SituationParticipantGroup": "ScopeSituationParticipantGroup",
    "SituationSubRegion": "ScopeSituationSubRegion",
    "StoryCycle": "ScopeStoryCycle", "Struggle": "ScopeStruggle",
    "TaskContract": "ScopeTaskContract",
    "TaskContractType": "ScopeTaskContractType",
    "TaxSlot": "ScopeTaxSlot",
    "TitleAndVassalChange": "ScopeTitleAndVassalChange",
    "Trait": "ScopeTrait", "TravelPlan": "ScopeTravelPlan",
    "VassalContract": "ScopeVassalContract",
    "VassalObligationLevel": "ScopeVassalObligationLevel",
    "War": "ScopeWar",
    "all": "ScopeAllScopes", "all_but_none": "ScopeAllScopes",
    "Bool": "ScopeValue", "Flag": "ScopeValue", "Value": "ScopeValue",
    "None": "ScopeValue",
}


def parse_scopes(expr):
    s = expr.replace("Scopes::", " ")
    parts = re.split(r'\.union\(|\.minus\(|\)', s)
    out = []
    for p in parts:
        p = p.strip()
        v = SCOPE_TO_GO.get(p)
        if v and v not in out:
            out.append(v)
    return out or ["ScopeAllScopes"]


def extract(filepath, const_name):
    with open(filepath, "r", encoding="utf-8") as f:
        c = f.read()
    idx = c.find(f"const {const_name}")
    idx = c.find("= &[", idx)
    if idx < 0:
        return ([], [])
    idx = c.find("[", idx)
    depth = 0
    start = idx
    for i in range(idx, len(c)):
        if c[i] == '[':
            depth += 1
        elif c[i] == ']':
            depth -= 1
            if depth == 0:
                block = c[start:i + 1]
                break

    pat = re.compile(r'\(\s*\n?\s*(Scopes::[^,]+?),\s*\n?\s*"([^"]+?)",\s*\n?\s*(Scopes::[^,)]+)')
    from_scopes = []
    to_scopes = []
    seen = set()
    for m in pat.finditer(block):
        in_scope, name, out_scope = m.groups()
        if name in seen:
            continue
        seen.add(name)
        in_s = parse_scopes(in_scope)
        out_s = parse_scopes(out_scope)
        from_scopes.append((name, in_s))
        to_scopes.append((name, out_s))
    return from_scopes, to_scopes


def main():
    from_s, to_s = extract(os.path.join(TIER, "targets.rs"), "SCOPE_TO_SCOPE")

    lines = []
    lines.append("// Code generated by tools/extract_targets.py; DO NOT EDIT.")
    lines.append(f"// Source: ck3-tiger targets.rs ({len(from_s)} scope transitions)")
    lines.append("")
    lines.append("package indexer")
    lines.append("")
    lines.append("// scopeTransitions maps event target names to their required input scope.")
    lines.append("var scopeTransitionsIn = map[string]TigerScope{")
    for key, scopes in sorted(from_s):
        val = " | ".join(scopes) if scopes else "ScopeAllScopes"
        lines.append(f'\t"{key}": {val},')
    lines.append("}")
    lines.append("")
    lines.append("// scopeTransitionsOut maps event target names to their output scope.")
    lines.append("var scopeTransitionsOut = map[string]TigerScope{")
    for key, scopes in sorted(to_s):
        val = " | ".join(scopes) if scopes else "ScopeAllScopes"
        lines.append(f'\t"{key}": {val},')
    lines.append("}")
    lines.append("")
    lines.append(f"// Generated {len(from_s)} scope transition entries")

    for line in lines:
        print(line)


if __name__ == "__main__":
    main()
