"""Generate CK3 scope metadata from an engine log bundle.

The engine logs are the canonical source for this table.  In particular,
``Supported Targets`` on trigger/effect iterator entries records the child
scope, so the generated table needs no fallback source.
"""

import argparse
import pathlib
import re


SCOPE_ALIASES = {
    "boolean": "value",
    "bool": "value",
    "flag": "value",
    "none": "value",
    "ghw": "great_holy_war",
    "landed_title": "title",
    "story": "story_cycle",
    "title_scope": "title",
    "county_title": "title",
    "province_scope": "province",
    "character_scope": "character",
    "vassal_contract_obligation_level": "vassal_obligation_level",
}


def canonical_scope(name):
    name = name.strip().lower()
    if name in ("", "all", "all_but_none"):
        return "all"
    return SCOPE_ALIASES.get(name, name)


def go_scope(name):
    name = canonical_scope(name)
    if name == "all":
        return "ScopeAllScopes"
    return "Scope" + "".join(part.title() for part in name.split("_"))


def go_scope_expr(scopes):
    scopes = sorted(set(scopes))
    if not scopes or "all" in scopes:
        return "ScopeAllScopes"
    values = [go_scope(scope) for scope in scopes]
    if len(values) == 1:
        return values[0]
    return "scopeUnion(" + ", ".join(values) + ")"


def read_blocks(path):
    blocks, current = [], []
    # Paradox's exported descriptions occasionally contain legacy Windows
    # punctuation. Rule names and scope labels are ASCII, so replacement is
    # safer than refusing an otherwise complete engine log bundle.
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line.startswith("----------------"):
            if current:
                blocks.append(current)
                current = []
        elif line:
            current.append(line)
    if current:
        blocks.append(current)
    return blocks


def entry_name(head):
    name = head.split(" - ", 1)[0].strip().rstrip(":").lower()
    # Logs include prose headings such as "Event Targets Saved from code:".
    # They are documentation sections, not script keys.
    return name if re.fullmatch(r"[a-z0-9_]+", name) else ""


def scopes_for(line, prefixes):
    for prefix in prefixes:
        if line.startswith(prefix):
            raw = line[len(prefix):].strip()
            return [canonical_scope(item) for item in re.split(r"[,|\s]+", raw) if item]
    return []


def read_rules(path, kind):
    rules = {}
    for block in read_blocks(path):
        if not block:
            continue
        name = entry_name(block[0])
        if not name or name.endswith("documentation"):
            continue
        inputs, outputs = [], []
        for line in block[1:]:
            inputs = inputs or scopes_for(line, ("Supported Scopes:", "Input Scopes:", "Expected Scope:"))
            outputs = outputs or scopes_for(line, ("Supported Targets:", "Output Scopes:"))
        rules[name] = (inputs, outputs)
    return rules


def is_iterator(name):
    return name.startswith(("any_", "every_", "random_", "ordered_"))


def iterator_names(path):
    names = set()
    for block in read_blocks(path):
        if not block:
            continue
        name = entry_name(block[0])
        syntax = " ".join(block).lower()
        has_child_script = "<triggers>" in syntax or "<effects>" in syntax
        has_child_scope = any(line.startswith("Supported Targets:") for line in block[1:])
        if name and has_child_script and has_child_scope:
            names.add(name)
    return names


def read_scope_names(path):
    names = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        match = re.fullmatch(r"([a-z_]+):", line)
        if match:
            names.append(match.group(1))
    return names


def emit_scope_data(scope_names, trigger_rules, effect_rules, iterator_set):
    concrete = sorted({canonical_scope(name) for name in scope_names if canonical_scope(name) != "all"})
    if "value" not in concrete:
        concrete.append("value")
        concrete.sort()
    constants = [go_scope(name) for name in concrete]
    lines = [
        "// Code generated by tools/extract_engine_scopes.py; DO NOT EDIT.",
        "// Source: CK3 1.19 engine event_scopes.log, triggers.log, and effects.log.",
        "",
        "package indexer",
        "",
        "// EngineScope is the indexer's lossless 128-bit scope set. The name is",
        "// retained for API compatibility; its members are generated from CK3 logs.",
        "type EngineScope struct {",
        "\tLow  uint64",
        "\tHigh uint64",
        "}",
        "",
        "var engineScopesByName = map[string]EngineScope{",
    ]
    for name in concrete:
        lines.append(f'\t"{name}": {go_scope(name)},')
    for alias, canonical in sorted(SCOPE_ALIASES.items()):
        lines.append(f'\t"{alias}": {go_scope(canonical)},')
    lines += [
        "}",
        "",
        "func scopeBit(bit int) EngineScope {",
        "\tif bit < 64 {",
        "\t\treturn EngineScope{Low: uint64(1) << bit}",
        "\t}",
        "\treturn EngineScope{High: uint64(1) << (bit - 64)}",
        "}",
        "",
        "func scopeUnion(scopes ...EngineScope) EngineScope {",
        "\tvar out EngineScope",
        "\tfor _, scope := range scopes {",
        "\t\tout.Low |= scope.Low",
        "\t\tout.High |= scope.High",
        "\t}",
        "\treturn out",
        "}",
        "",
        "func (scope EngineScope) IsZero() bool { return scope.Low == 0 && scope.High == 0 }",
        "func (scope EngineScope) Intersects(other EngineScope) bool {",
        "\treturn scope.Low&other.Low != 0 || scope.High&other.High != 0",
        "}",
        "",
        "var (",
    ]
    for index, constant in enumerate(constants):
        lines.append(f"\t{constant:<34} = scopeBit({index})")
    lines += [
        "\tScopeAllScopes = EngineScope{Low: ^uint64(0), High: ^uint64(0)}",
        ")",
        "",
        "var engineScopeNames = []struct {",
        "\tName  string",
        "\tScope EngineScope",
        "}{",
    ]
    for name in concrete:
        lines.append(f'\t{{Name: "{name}", Scope: {go_scope(name)}}},')
    lines += ["}", ""]

    def emit_map(comment, var_name, entries):
        lines.extend([f"// {comment}", f"var {var_name} = map[string]EngineScope{{"])
        for name, scopes in sorted(entries.items()):
            lines.append(f'\t"{name}": {go_scope_expr(scopes)},')
        lines.extend(["}", ""])

    emit_map("CK3 1.19 trigger input scopes.", "engineTriggerScopes", {key: value[0] for key, value in trigger_rules.items()})
    emit_map("CK3 1.19 effect input scopes.", "engineEffectScopes", {key: value[0] for key, value in effect_rules.items()})
    iterators = {**trigger_rules, **effect_rules}
    emit_map("CK3 1.19 iterator input scopes.", "engineIteratorScopeIn", {key: value[0] for key, value in iterators.items() if key in iterator_set})
    emit_map("CK3 1.19 iterator output scopes from Supported Targets.", "engineIteratorScopeOut", {key: value[1] for key, value in iterators.items() if key in iterator_set and value[1]})
    lines += [
        "var iteratorScopeIn = engineIteratorScopeIn",
        "var iteratorScopeOut = engineIteratorScopeOut",
        "",
    ]
    return "\n".join(lines) + "\n"
def emit_targets(targets):
    lines = [
        "// Code generated by tools/extract_engine_scopes.py; DO NOT EDIT.",
        "// Source: CK3 1.19 engine event_targets.log.",
        "",
        "package indexer",
        "",
        "// engineScopeTransitions maps CK3 1.19 event target input and output scopes.",
        "var engineScopeTransitionsIn = map[string]EngineScope{",
    ]
    for name, (inputs, _) in sorted(targets.items()):
        lines.append(f'\t"{name}": {go_scope_expr(inputs)},')
    lines += ["}", "", "var engineScopeTransitionsOut = map[string]EngineScope{"]
    for name, (_, outputs) in sorted(targets.items()):
        if outputs:
            lines.append(f'\t"{name}": {go_scope_expr(outputs)},')
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--logs", required=True, type=pathlib.Path)
    parser.add_argument("--scope-output", required=True, type=pathlib.Path)
    parser.add_argument("--targets-output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    scope_names = read_scope_names(args.logs / "event_scopes.log")
    trigger_log = args.logs / "triggers.log"
    effect_log = args.logs / "effects.log"
    triggers = read_rules(trigger_log, "trigger")
    effects = read_rules(effect_log, "effect")
    iterators = iterator_names(trigger_log) | iterator_names(effect_log)
    targets = read_rules(args.logs / "event_targets.log", "target")
    args.scope_output.write_text(emit_scope_data(scope_names, triggers, effects, iterators), encoding="utf-8", newline="\n")
    args.targets_output.write_text(emit_targets(targets), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
