"""Generate the modifier lookup manifest from CK3 1.19 evidence.

The engine's ``modifiers.log`` supplies documented use areas.  Current
``common/modifier_definition_formats`` supplies concrete modifier names, which
is essential for tags generated from documented ``$TOKEN$`` templates (for
example the subject-salary variants).  No legacy static data is read.
"""

import argparse
import json
import pathlib
import re


TOP_LEVEL_FORMAT = re.compile(r"^\s*([A-Za-z0-9_]+)\s*=\s*\{")


def normalize_areas(raw: str) -> list[str]:
    """Split the localized separators emitted by the 1.19 documentation log."""
    normalized = raw.replace("，", ",").replace("以及", ",")
    out: list[str] = []
    for value in normalized.split(","):
        value = value.strip()
        if value and value not in out:
            out.append(value)
    return out


def read_log(path: pathlib.Path) -> list[tuple[str, list[str]]]:
    """Read Tag / Use areas records even when Extra info separates the lines."""
    records: list[tuple[str, list[str]]] = []
    active_tag = ""
    seen: set[str] = set()
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line.startswith("Tag:"):
            active_tag = line.removeprefix("Tag:").strip()
        elif active_tag and line.startswith("Use areas:"):
            if active_tag not in seen:
                records.append((active_tag, normalize_areas(line.removeprefix("Use areas:").strip())))
                seen.add(active_tag)
            active_tag = ""
    return records


def current_format_keys(game: pathlib.Path) -> set[str]:
    """Return direct top-level modifier-definition-format keys from vanilla."""
    root = game / "common" / "modifier_definition_formats"
    if not root.is_dir():
        raise SystemExit(f"missing current modifier format sources: {root}")
    out: set[str] = set()
    for path in sorted(root.rglob("*.txt")):
        depth = 0
        for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw.lstrip("\ufeff").split("#", 1)[0]
            if depth == 0:
                match = TOP_LEVEL_FORMAT.match(line)
                if match:
                    out.add(match.group(1))
            depth += line.count("{") - line.count("}")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--logs", required=True, type=pathlib.Path)
    parser.add_argument("--game", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    log_path = args.logs / "modifiers.log"
    if not log_path.is_file():
        raise SystemExit(f"missing current CK3 modifier log: {log_path}")
    records = read_log(log_path)
    if not records:
        raise SystemExit(f"no modifier records found in: {log_path}")
    format_keys = current_format_keys(args.game)

    # Preserve documented template IDs for explicit reference queries, then
    # add every current concrete format key. A $TOKEN$ log tag does not prove
    # which concrete names the engine will substitute for that token: broad
    # templates such as $TAX_SLOT_TYPE$_add can match many unrelated names.
    # Therefore only exact current tag names inherit a log use-area contract;
    # every format-only name remains found with an explicitly unknown area.
    modifiers: dict[str, tuple[list[str], str]] = {
        tag: (areas, "engine_log") for tag, areas in records
    }
    for key in sorted(format_keys):
        if key in modifiers:
            modifiers[key] = (modifiers[key][0], "engine_log+vanilla_modifier_format")
        else:
            modifiers[key] = ([], "vanilla_modifier_format")

    lines = [
        "// Code generated by tools/extract_modifiers.py; DO NOT EDIT.",
        "// Source: CK3 1.19 modifiers.log plus current common/modifier_definition_formats.",
        "",
        "package indexer",
        "",
        "// ModifierInfo describes a current CK3 modifier tag and its evidence.",
        "type ModifierInfo struct {",
        '\tUseAreas []string `json:"use_areas"`',
        '\tSource string `json:"source"`',
        "}",
        "",
        "// engineModifiers maps documented and current concrete modifier tags.",
        "var engineModifiers = map[string]ModifierInfo{",
    ]
    for tag, (areas, source) in sorted(modifiers.items()):
        area_values = ", ".join(json.dumps(area) for area in areas)
        lines.append(
            f"\t{json.dumps(tag)}: {{UseAreas: []string{{{area_values}}}, Source: {json.dumps(source)}}},"
        )
    lines += [
        "}",
        "",
        f"// {len(records)} documented tags, {len(format_keys)} current format keys, {len(modifiers)} lookup entries",
    ]
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
