"""Extract on_action names from ck3-tiger on_action.rs."""

import re, os
BASE = os.path.dirname(os.path.abspath(__file__))
TIER = os.path.join(BASE, "..", "external", "ck3-tiger", "src", "ck3", "tables")

def main():
    with open(os.path.join(TIER, "on_action.rs"), "r", encoding="utf-8") as f:
        c = f.read()
    # Find the raw string literal content
    idx = c.find("ON_ACTION_SCOPES")
    idx = c.find('"', idx) + 1
    end_str = c.find('";', idx)
    if end_str < 0: end_str = c.rfind('"')
    text = c[idx:end_str]

    # Parse: on_xxx = { root = scope_type ... }
    # or: on_xxx = on_yyy  (alias)
    pat = re.compile(r'^\s*(\w+)\s*=\s*\{', re.MULTILINE)
    alias_pat = re.compile(r'^\s*(\w+)\s*=\s*(\w+)', re.MULTILINE)
    
    on_actions = set()
    for m in pat.finditer(text):
        on_actions.add(m.group(1))
    for m in alias_pat.finditer(text):
        if m.group(2) in on_actions:
            on_actions.add(m.group(1))

    lines = []
    lines.append("// Code generated by tools/extract_on_actions.py; DO NOT EDIT.")
    lines.append(f"// Source: ck3-tiger on_action.rs ({len(on_actions)} entries)")
    lines.append("package indexer")
    lines.append("")
    lines.append("var tigerOnActions = map[string]struct{}{")
    for name in sorted(on_actions):
        lines.append(f'\t"{name}": {{}},')
    lines.append("}")
    lines.append(f"// {len(on_actions)} on_action entries")

    for line in lines:
        print(line)

if __name__ == "__main__":
    main()
