"""Extract sounds, localization macros, and misc data from ck3-tiger."""

import re, os
BASE = os.path.dirname(os.path.abspath(__file__))
TIER = os.path.join(BASE, "..", "external", "ck3-tiger", "src", "ck3", "tables")

def extract_sounds():
    with open(os.path.join(TIER, "sounds.rs"), "r", encoding="utf-8") as f:
        c = f.read()
    idx = c.find("const SOUNDS: &[&str]")
    idx = c.find("&[", idx); idx = c.find("[", idx) + 1
    end = c.find("];", idx)
    block = c[idx:end]
    sounds = sorted(set(re.findall(r'"([^"]+)"', block)))
    return sounds

def extract_macros():
    with open(os.path.join(TIER, "localization.rs"), "r", encoding="utf-8") as f:
        c = f.read()
    idx = c.find("const BUILTIN_MACROS: &[&str]")
    idx = c.find("&[", idx); idx = c.find("[", idx) + 1
    end = c.find("];", idx)
    block = c[idx:end]
    macros = sorted(set(re.findall(r'"([^"]+)"', block)))
    return macros

def main():
    sounds = extract_sounds()
    macros = extract_macros()

    lines = []
    lines.append("// Code generated by tools/extract_tiger_extra.py; DO NOT EDIT.")
    lines.append(f"// Source: ck3-tiger sounds.rs + localization.rs")
    lines.append("package indexer")
    lines.append("")
    lines.append(f"// tigerSounds has valid CK3 sound event names.")
    lines.append(f"var tigerSounds = map[string]struct{{}}{{")
    for s in sounds:
        safe = s.replace("\\","\\\\").replace('"','\\"')
        lines.append(f'\t"{safe}": {{}},')
    lines.append("}")
    lines.append(f"// {len(sounds)} sound entries")
    lines.append("")
    lines.append(f"// tigerLocMacros has built-in CK3 localization macro names.")
    lines.append(f"var tigerLocMacros = map[string]struct{{}}{{")
    for m in macros:
        lines.append(f'\t"{m}": {{}},')
    lines.append("}")
    lines.append(f"// {len(macros)} macro entries")

    for line in lines:
        print(line)

if __name__ == "__main__":
    main()
