"""Extract modifier scope kinds from ck3-tiger modifs.rs."""

import re, os
BASE = os.path.dirname(os.path.abspath(__file__))
TIER = os.path.join(BASE, "..", "external", "ck3-tiger", "src", "ck3", "tables")

KIND_MAP = {
    "Character": "character", "Province": "province", "County": "county",
    "Duchy": "duchy", "Kingdom": "kingdom", "Empire": "empire",
    "Culture": "culture", "Faith": "faith", "Dynasty": "dynasty",
    "House": "house", "HolyOrder": "holy_order", "Religion": "religion",
    "Title": "title", "War": "war", "Artifact": "artifact",
    "Scheme": "scheme", "Secret": "secret", "Struggle": "struggle",
    "Activity": "activity", "Army": "army", "Combat": "combat",
    "Story": "story", "Legend": "legend", "Accolade": "accolade",
    "TravelPlan": "travel_plan", "Domicile": "domicile",
    "TaskContract": "task_contract", "Faction": "faction",
    "Inspiration": "inspiration", "Memory": "memory",
    "MercenaryCompany": "mercenary_company", "HolyWar": "holy_war",
    "all": "any",
}

def parse_kinds(expr):
    parts = re.split(r'\.union\(|\)', expr.replace("ModifKinds::", ""))
    kinds = []
    for p in parts:
        p = p.strip()
        if p in KIND_MAP:
            v = KIND_MAP[p]
            if v not in kinds and v != "any":
                kinds.append(v)
    return kinds or ["any"]

def main():
    with open(os.path.join(TIER, "modifs.rs"), "r", encoding="utf-8") as f:
        c = f.read()
    
    idx = c.find("const MODIF_TABLE")
    idx = c.find("= &[", idx)
    idx = c.find("[", idx)
    depth = 0
    for i in range(idx, len(c)):
        if c[i] == '[': depth += 1
        elif c[i] == ']':
            depth -= 1
            if depth == 0: block = c[idx:i+1]; break

    pat = re.compile(r'\(\s*"([^"]+)"\s*,\s*(ModifKinds::[^,\)]+(?:\s*\.union\([^\)]+\))*)\s*\)')
    modifs = []
    seen = set()
    for m in pat.finditer(block):
        name, kind_expr = m.groups()
        if name in seen: continue
        seen.add(name)
        kinds = parse_kinds(kind_expr)
        modifs.append((name, kinds))

    # Also parse removed modifiers
    idx2 = c.find("const MODIF_REMOVED_TABLE")
    idx2 = c.find("&[", idx2); idx2 = c.find("[", idx2)
    depth = 0
    for i in range(idx2, len(c)):
        if c[i] == '[': depth += 1
        elif c[i] == ']':
            depth -= 1
            if depth == 0: rem_block = c[idx2:i+1]; break
    rem_pat = re.compile(r'\(\s*"([^"]+)"\s*,')
    for m in rem_pat.finditer(rem_block):
        name = m.group(1)
        modifs.append((name, ["removed"]))

    lines = []
    lines.append("// Code generated by tools/extract_tiger_modifs.py; DO NOT EDIT.")
    lines.append(f"// Source: ck3-tiger modifs.rs ({len(modifs)} entries)")
    lines.append("package indexer")
    lines.append("")
    lines.append("// tigerModifKinds maps modifier tags to their valid scope kinds.")
    lines.append("var tigerModifKinds = map[string][]string{")
    for name, kinds in sorted(modifs):
        k = ", ".join(f'"{x}"' for x in kinds)
        lines.append('\t"' + name + '": {' + k + '},')
    lines.append("}")
    lines.append(f"// {len(modifs)} modifier entries")

    for line in lines:
        print(line)

if __name__ == "__main__":
    main()
