"""Generate the CK3 sound-event manifest from current vanilla evidence.

The FMOD GUID catalogue proves registered events; current game text supplies
literal event paths used by scripts, GUI, and music definitions.  Both are
versioned with the installed CK3 game.
"""

import argparse
import json
import pathlib
import re


# CK3 FMOD event paths use this conservative path alphabet.  Keeping the
# delimiter out of the match prevents list closers such as `]` becoming fake
# sound IDs when scanning Jomini arrays.
EVENT = re.compile(r"event:/[A-Za-z0-9_./-]+")
TEXT_EXTENSIONS = {".txt", ".gui", ".asset", ".yml", ".yaml", ".audio2"}


def read_events(path: pathlib.Path) -> set[str]:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return set()
    events = set()
    for match in EVENT.finditer(text):
        event = match.group(0).rstrip(",")
        # Keep literal engine paths, not the placeholder convention used in
        # comments such as event://path/to/fmod_event.
        if event.startswith("event://") or "/path/to/" in event:
            continue
        events.add(event)
    return events


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    guid_path = args.game / "sound" / "GUIDs.txt"
    if not guid_path.is_file():
        raise SystemExit(f"missing current CK3 sound catalogue: {guid_path}")

    events = read_events(guid_path)
    source_files = 1
    for path in args.game.rglob("*"):
        if not path.is_file() or path == guid_path or path.suffix.lower() not in TEXT_EXTENSIONS:
            continue
        found = read_events(path)
        if found:
            source_files += 1
            events.update(found)

    lines = [
        "// Code generated by tools/extract_engine_sounds.py; DO NOT EDIT.",
        f"// Source: CK3 1.19 sound/GUIDs.txt plus {source_files - 1} current vanilla text files with event references.",
        "",
        "package indexer",
        "",
        "// engineSounds contains CK3 1.19 sound event paths proven by current vanilla files.",
        "var engineSounds = map[string]struct{}{",
    ]
    for event in sorted(events):
        lines.append(f"\t{json.dumps(event)}: {{}},")
    lines += ["}", "", f"// {len(events)} current sound events"]
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
