"""Generate current CK3 trigger usage examples from triggers.log."""

import argparse
import pathlib
import re


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--logs", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    logpath = args.logs / "triggers.log"
    if not logpath.is_file():
        raise SystemExit(f"missing current CK3 trigger documentation: {logpath}")

    content = logpath.read_text(encoding="utf-8", errors="replace")
    entries: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for section in content.split("--------------------"):
        lines = [line.strip() for line in section.strip().split("\n") if line.strip()]
        if not lines:
            continue
        match = re.match(r"(\w+)\s*-\s*(.*)", lines[0])
        if not match:
            continue
        name, desc = match.group(1).strip(), match.group(2).strip()
        if name in seen:
            continue
        seen.add(name)
        example = ""
        for line in lines[1:]:
            if "=" in line and not line.startswith("Supported Scopes"):
                candidate = line.strip()
                if candidate.startswith(name):
                    example = candidate
                    break
        entries.append((name, desc, example))

    lines = [
        "// Code generated by tools/extract_trigger_examples.py; DO NOT EDIT.",
        f"// Source: CK3 1.19 triggers.log ({len(entries)} triggers).",
        "",
        "package indexer",
        "",
        "// triggerExamples maps trigger names to current documented usage examples.",
        "var triggerExamples = map[string]struct{ Desc, Example string }{",
    ]
    for name, desc, example in sorted(entries):
        desc = desc.replace("`", "'").replace("\n", " ").replace("\r", "").replace("\ufffd", "?")
        if example:
            example = example.replace("`", "'").replace("\n", " ").replace("\r", "").replace("\ufffd", "?")
            lines.append(f'\t"{name}": {{Desc: `{desc}`, Example: `{example}`}},')
        else:
            lines.append(f'\t"{name}": {{Desc: `{desc}`}},')
    lines += ["}", "", f"// {len(entries)} current trigger entries"]
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
