"""Generate on_action evidence from CK3 engine logs and vanilla source.

The log supplies the complete membership and root scope. Adjacent comments in
the current vanilla on_action files may additionally prove literal named/list
targets. Unannotated targets are intentionally omitted instead of inheriting
an older static table.
"""

import argparse
import json
import pathlib
import re


ROOT = re.compile(r"^\s*#\s*Root\s*=\s*(.+?)\s*$", re.IGNORECASE)
TARGETS = re.compile(r"^\s*#\s*(Event|List)\s+targets?\s*:\s*(.+?)\s*$", re.IGNORECASE)
TOP_LEVEL = re.compile(r"^\s*([A-Za-z0-9_]+)\s*=\s*\{")
TYPE = re.compile(r"^\s*([A-Za-z0-9_]+)\s*\(\s*([^()]+?)\s*\)\s*$")

TYPE_ALIASES = {
    "landed title": "landed_title",
    "landed_title": "landed_title",
    "title": "landed_title",
    "yes/no": "bool",
    "boolean": "bool",
    "bool": "bool",
    "flag": "flag",
    "value": "value",
    "none": "none",
    "ghw": "ghw",
}


def read_blocks(path):
    blocks, current = [], []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line.startswith("----------------"):
            if current:
                blocks.append(current)
                current = []
        elif line:
            current.append(line)
    if current:
        blocks.append(current)
    return blocks


def log_actions(path):
    out = {}
    for block in read_blocks(path):
        if not block:
            continue
        name = block[0].rstrip(":").strip().lower()
        if not name or name.endswith("documentation"):
            continue
        root = "none"
        for line in block[1:]:
            if line.startswith("Expected Scope:"):
                root = normalize_type(line.split(":", 1)[1])
                break
        out[name] = root
    return out


def normalize_type(value):
    value = value.strip().lower().replace("-", "_")
    value = re.sub(r"\s+", "_", value)
    return TYPE_ALIASES.get(value, value)


def brace_delta(line):
    quoted = False
    escaped = False
    delta = 0
    for char in line:
        if quoted:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                quoted = False
            continue
        if char == "#":
            break
        if char == '"':
            quoted = True
        elif char == "{":
            delta += 1
        elif char == "}":
            delta -= 1
    return delta


def documented_bindings(comments):
    root = None
    named, lists = [], []
    for comment in comments:
        if match := ROOT.match(comment):
            root = normalize_type(match.group(1))
        if match := TARGETS.match(comment):
            destination = lists if match.group(1).lower() == "list" else named
            for item in match.group(2).split(","):
                typed = TYPE.match(item)
                if not typed:
                    continue
                name, value_type = typed.groups()
                destination.append((name.strip().lower(), normalize_type(value_type)))
    return root, named, lists


def vanilla_comments(game):
    docs = {}
    for path in sorted((game / "common" / "on_action").rglob("*.txt")):
        depth = 0
        comments = []
        for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = raw.strip()
            if depth == 0 and stripped.startswith("#"):
                comments.append(stripped)
                continue
            if depth == 0 and (match := TOP_LEVEL.match(raw)):
                root, named, lists = documented_bindings(comments)
                docs[match.group(1).lower()] = (root, named, lists)
                comments = []
            elif depth == 0 and stripped:
                comments = []
            depth += brace_delta(raw)
            if depth < 0:
                raise ValueError(f"unbalanced braces in {path}")
    return docs


def kind(value_type):
    if value_type == "none":
        return "OnActionSnapshotValueKindNone"
    if value_type == "flag":
        return "OnActionSnapshotValueKindFlag"
    if value_type == "value":
        return "OnActionSnapshotValueKindValue"
    if value_type == "bool":
        return "OnActionSnapshotValueKindBool"
    return "OnActionSnapshotValueKindScope"


def binding(name, value_type):
    return "onActionSnapshotBindingSeed{" + ", ".join([
        f"Name: {json.dumps(name)}",
        f"StaticType: {json.dumps(value_type)}",
        f"Kind: {kind(value_type)}",
    ]) + "}"


def emit(actions, docs):
    documented = sum(1 for name in actions if name in docs)
    typed = sum(len(named) + len(lists) for _, named, lists in docs.values())
    lines = [
        "// Code generated by tools/extract_engine_on_actions.py; DO NOT EDIT.",
        f"// Source: CK3 1.19 on_actions.log ({len(actions)} entries) plus {documented} current vanilla comment contracts ({typed} typed bindings).",
        "package indexer",
        "",
        'const engineOnActionSnapshotVersion = "1.19.0-engine-log"',
        "",
        "// Every entry below was generated from CK3 1.19 engine evidence.",
        "var engineOnActions = map[string]struct{}{",
    ]
    for name in sorted(actions):
        lines.append(f"\t{json.dumps(name)}: {{}},")
    lines += ["}", "", "var engineOnActionDirect = map[string]onActionSnapshotDirectSeed{"]
    for name, log_root in sorted(actions.items()):
        documented_root, named, lists = docs.get(name, (None, [], []))
        # The log is authoritative. A disagreeing vanilla comment must not
        # override it; the audit exposes such disagreements separately.
        lines.append(f"\t{json.dumps(name)}: {{")
        lines.append(f"\t\tRoot: {binding('root', log_root)},")
        if named:
            lines.append("\t\tNamed: []onActionSnapshotBindingSeed{")
            for target, value_type in named:
                lines.append(f"\t\t\t{binding(target, value_type)},")
            lines.append("\t\t},")
        if lists:
            lines.append("\t\tLists: []onActionSnapshotBindingSeed{")
            for target, value_type in lists:
                lines.append(f"\t\t\t{binding(target, value_type)},")
            lines.append("\t\t},")
        lines.append("\t},")
    lines += ["}", "", "// Engine logs expose concrete hook ids, so aliases are not inferred.", "var engineOnActionAliases = map[string]onActionSnapshotAliasSeed{}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--logs", required=True, type=pathlib.Path)
    parser.add_argument("--game", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    args.output.write_text(emit(log_actions(args.logs / "on_actions.log"), vanilla_comments(args.game)), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
