"""Extract static modifier definitions from CK3's modifiers.log dump.

Usage: python extract_modifiers.py > ../internal/indexer/modifiers_data.gen.go
"""

import re, os, sys

def main():
    logpath = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "logs", "modifiers.log")
    if not os.path.exists(logpath):
        # Try alternate paths
        logpath = os.path.join(os.path.dirname(__file__), "..", "..", "..", "logs", "modifiers.log")
    if not os.path.exists(logpath):
        logpath = os.path.join(os.path.dirname(__file__), "..", "..", "logs", "modifiers.log")
    if not os.path.exists(logpath):
        print("// ERROR: modifiers.log not found", file=sys.stderr)
        return

    with open(logpath, "r", encoding="utf-8") as f:
        content = f.read()

    # Parse: Tag: name \n Use areas: scope1, scope2, ...
    pattern = re.compile(r'Tag:\s*(.+?)\nUse areas:\s*(.+?)\n', re.MULTILINE)
    modifiers = []
    seen = set()
    for m in pattern.finditer(content):
        tag = m.group(1).strip()
        areas = [a.strip() for a in m.group(2).split(',')]
        if tag not in seen:
            seen.add(tag)
            modifiers.append((tag, areas))

    lines = []
    lines.append("// Code generated by tools/extract_modifiers.py; DO NOT EDIT.")
    lines.append(f"// Source: CK3 modifiers.log ({len(modifiers)} modifier tags)")
    lines.append("")
    lines.append("package indexer")
    lines.append("")
    lines.append("// ModifierInfo describes a static modifier tag.")
    lines.append("type ModifierInfo struct {")
    lines.append("\tUseAreas []string `json:\"use_areas\"`")
    lines.append("}")
    lines.append("")
    lines.append("// tigerModifiers maps modifier tag names to their valid use areas.")
    lines.append("var tigerModifiers = map[string]ModifierInfo{")
    for tag, areas in sorted(modifiers):
        areaStr = ", ".join(f'"{a}"' for a in areas)
        lines.append(f'\t"{tag}": {{UseAreas: []string{{{areaStr}}}}},')
    lines.append("}")
    lines.append("")
    lines.append(f"// {len(modifiers)} modifier entries")

    for line in lines:
        print(line)

if __name__ == "__main__":
    main()
