"""Extract define names and types from ck3-tiger defines.rs."""

import re, os
BASE = os.path.dirname(os.path.abspath(__file__))
TIER = os.path.join(BASE, "..", "external", "ck3-tiger", "src", "ck3", "tables")

def main():
    with open(os.path.join(TIER, "defines.rs"), "r", encoding="utf-8") as f:
        c = f.read()
    idx = c.find("const DEFINES: &[")
    idx = c.find("= &[", idx)  # skip type annotation, find actual array
    idx = c.find("[", idx)
    depth = 0
    for i in range(idx, len(c)):
        if c[i] == '[': depth += 1
        elif c[i] == ']':
            depth -= 1
            if depth == 0: block = c[idx:i+1]; break

    pat = re.compile(r'\(\s*"([^"]+)"\s*,\s*DefineType::(\w+)\s*\)')
    defines = pat.findall(block)
    seen = set()
    deduped = []
    for name, typ in defines:
        if name not in seen:
            seen.add(name)
            deduped.append((name, typ))
    defines = deduped

    lines = []
    lines.append("// Code generated by tools/extract_defines.py; DO NOT EDIT.")
    lines.append(f"// Source: ck3-tiger defines.rs ({len(defines)} entries)")
    lines.append("package indexer")
    lines.append("")
    lines.append("var tigerDefines = map[string]struct{}{")
    for name, typ in sorted(defines):
        lines.append(f'\t"@{name}": {{}},')
    lines.append("}")
    lines.append(f"// {len(defines)} define entries")

    for line in lines:
        print(line)

if __name__ == "__main__":
    main()
